Print ocean node logs.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -186,4 +186,13 @@ jobs:
           INDEXING_MAX_RETRIES: 120
           NODE_URL: 'http://127.0.0.1:8001'
           AVOID_LOOP_RUN: true
-
+      - name: Print Ocean Node Logs if tests fail
+        if: ${{ failure() }}
+        run: |
+          echo "========== Ocean Node Logs =========="
+          tac ${{ github.workspace }}/ocean-node/ocean-node.log || echo "Log file not found"
+      - name: Upload coverage
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-integration
+          path: coverage/
