Feature/paid-compute in cli (#115)
* Create initializeCompute command and refator computeStart command.

* Fix config and imports from ocean.js in the commands.

* Added checks for escrow and porvider fees in compute start command.

* Make exports work.

* Fix await.

* Fix asset and ddo types.

* Update publish script.

* Update workflow to not use old c2d.

* Added tests for compute environments and fix ci.

* Fix branch for node.

* Correct ci.

* Print ocean node logs.

* Fix import.

* Added test for initialize and get compute envs.

* Rename tests suit.

* Add test for start compute.

* Changed publish approach command.

* Print ocean node logs in ci.

* Update examples with indexedMetadata.

* Replace with runCommand.

* Increased timeout.

* Debug logs for compute dataset.

* Fix retrieval for did.

* Remove eval.

* Debug getDDO command.

* Updated test.

* Updated test.

* debug.

* Trim response from get compute envs response.

* Added validation for fields in initialize command and start compute. Fixed tests parsing.

* Update setup and cli.

* Fix condition.

* Fix resources.

* Modified config and updated test.

* Add logs in initialize.

* Refactor condition.

* Fix stringified resources.

* Update import.

* Fix envs.

* Debug command initialize.

* Modified test.

* stringify in program command.

* Refactor parsing of initialize response.

* Added missing parameter from startCompute.

* Added one dash.

* Fix envs reponse + missing parameters from command.

* modified commands.

* Cleanup.

* debug start compute command.

* Fix name for amountToDeposit.

* Fix import between the test.

* Created util for tests.

* remove duplicate argument.

* debug parsing initialize response.

* Fix all tests, refactor code for startCompute. Added tests for compute status and get job results.

* Fix import.

* Cleanup + fix ci.

* Make agreement ID optional back.

* Update ocean.js

* Make amount to deposit optional.

* Incorporate initializeCommand in startCompute.

* Updated logic for startCompute command.

* Fix condition. Updated test.

* Fix amount.

* Fix print and lint.

* Fix option.

* Fix test.

* Fix test.

* Fix setup test.

* Fix README.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -121,8 +121,9 @@ jobs:
             sleep 10
             attempt=$((attempt + 1))
           done
+
       - name: docker logs
-        run: docker logs ocean-ocean-contracts-1 && docker logs ocean-ganache-1 && docker logs ocean-typesense-1 
+        run: docker logs ocean_ocean-contracts_1 && docker logs ocean_typesense_1
         if: ${{ failure() }}
 
       - name: Run system tests 
@@ -132,3 +133,8 @@ jobs:
           INDEXING_MAX_RETRIES: 120
           NODE_URL: 'http://127.0.0.1:8001'
           AVOID_LOOP_RUN: true
+      - name: Print Ocean Node Logs if tests fail
+        if: ${{ failure() }}
+        run: |
+          echo "========== Ocean Node Logs =========="
+          tac ${{ github.workspace }}/ocean-node/ocean-node.log || echo "Log file not found"
